### ISSUE TITLE
regarding  "plant_disease_model_1_latest.pt"

### ISSUE THREAD

**Issue by ramyaperumandla24** [manthan89-py/Plant-Disease-Detection#3]
@manthan89-py 
 Please could you share that "plant_disease_model_1_latest.pt" file? or that code ?Is it same as the model code which was present in the "Plant Disease Detection Code.ipynb" file? Please can you help me with this?

**Comment by mcjill** [comment]
Could you please share the "plant_disease_model_1_latest.pt" file or the code for it? Is it the same as the model code that was in the "Plant Disease Detection Code.ipynb" file? I would really appreciate your help with this.

**Comment by manthan89-py** [comment]
Yeah, I am sorry about that file. Because it is a too large file Github not allowing me to upload that file. So I have uploaded it on [Google Drive](https://drive.google.com/drive/folders/1ewJWAiduGuld_9oGSrTuLumg9y62qS6A?usp=share_link) and now you can download it easily.

**Comment by manthan89-py** [comment]
I have also added the same google drive link in the `Model` Section Readme file.
