### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Iyer2505** [manthan89-py/Plant-Disease-Detection#4]
@manthan89-py
Bro, i am getting error form the Batch Gradient Descent so help me with this bro..
https://user-images.githubusercontent.com/89437645/199702464-4c521816-9c45-40b8-a475-8d49c24a340e.jpeg

**Comment by dantas-ds** [comment]
You can fix it adding > **test_losses = np.zeros(epochs)** < inside the function, below the test_losses

**Comment by manthan89-py** [comment]
Yeah, Thanks for Pointing it out. It is a mistake on my side. I might have misconfigured the names test_losses and validation_losses. I will fix it and till then you can change the test_losses to validation_losses in the batch_gd function. I have attached a screenshot for your reference.

![Screenshot from 2023-04-09 10-08-46](https://user-images.githubusercontent.com/61309101/230754752-0d3fec81-9b2f-4df0-9ba3-a5b2c63bc2c8.png)
