### ISSUE TITLE
Batch Gradient descent

### ISSUE THREAD

**Issue by RS-VIJAY** [manthan89-py/Plant-Disease-Detection#5]
While running the code under batch gradient descent in pynb model. It is throwing the error validation_losses is not defined.
Can you please help me to resolve it.

**Comment by manthan89-py** [comment]
Yeah, Thanks for Pointing it out. It is a mistake on my side. I might have misconfigured the names test_losses and validation_losses. I will fix it and till then you can change the `test_losses` to `validation_losses` in the `batch_gd` function. I have attached a screenshot for your reference.

![Screenshot from 2023-04-09 10-08-46](https://user-images.githubusercontent.com/61309101/230754650-60ac1bf4-7c3f-4fd5-b1ac-67d5627aa1a7.png)
